chain_id: 1001
program_id: "CmobH2vR6aUtQ8x4xd1LYNiH6k2G7PFT5StTgWqvy2VU"
solana:
  rpc_url: "http://solana:8899"
payers:
  - payer_keypair: "/opt/rhea-sender.json"
    number_holders: 4
  - payer_keypair: "/opt/rhea-sender-2.json"
    number_holders: 16
  - payer_keypair: "/opt/rhea-sender-3.json"
    number_holders: 64
geth_indexer:
  geth_http_addr: "http://geth:8545"
  geth_poll_interval_ms: 100